export const searchKeys = [
  "chainName",
  "oracleType",
  "project",
  "title",
  "ancillaryData",
  "decodedAncillaryData",
  "timeUTC",
  "timeFormatted",
  "price",
  "expiryType",
  "currency",
  "formattedBond",
  "formattedReward",
  "assertion",
];
